"""adds Book model

Revision ID: 66deb2ec0b52
Revises: 
Create Date: 2025-10-23 15:23:03.015291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66deb2ec0b52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
